
@baseUrl = http://localhost:7001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoi5rWL6K-V5rWL6K-VNiIsIm5pY2tuYW1lIjoi5pi156ew5rWL6K-VNiIsImVtYWlsIjoi6YKu566x6YKu566xNiIsImF2YXRhciI6IiIsInBob25lIjoiIiwic2V4Ijoi55S3Iiwic3RhdHVzIjoxLCJzaWduIjoiIiwiYXJlYSI6IiIsImNyZWF0ZWRfYXQiOiIyMDIwLTExLTA1VDA2OjUxOjQwLjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMC0xMS0wNVQwNjo1MTo0MC4wMDBaIiwicGFzc3dvcmQiOiJlMGJjNjBjODI3MTNmNjRlZjhhNTdjMGM0MGQwMmNlMjRmZDAxNDFkNWNjMzA4NjI1OWMxOWIxZTYyYTYyYmVhIiwiaWF0IjoxNjA1NTg0Njc2fQ.0_-ATerY8JeVy0kuUPEvUmAFBW1gDC-WyeagGp2KX9U

### 基础测试API
# 查用户列表
GET http://localhost:7001/api/test HTTP/1.1
###
# 新增用户
POST http://localhost:7001/api/test HTTP/1.1
###
# 查用户详情
GET http://localhost:7001/api/test/1 HTTP/1.1
###
# 更新用户
PUT http://localhost:7001/api/test/1 HTTP/1.1
Content-Type: application/json

{
  "username": "测试23",
  "avatar": "hhhhhh",
  "password": "我想改密码，但是改不了",
  "fuck": "fuck"
}
###
# 删除用户
DELETE http://localhost:7001/api/test/1 HTTP/1.1
###
# 访问无效API
GET http://localhost:7001/api/fuck HTTP/1.1
###
# 原生 SQL 查询
GET http://localhost:7001/api/rawSqlGetApplyWithUser HTTP/1.1
token: {{token}}
###
# 原生 SQL 更新
PUT http://localhost:7001/api/rawSqlUpdateUser HTTP/1.1
token: {{token}}
###
# 原生 SQL 新增
POST http://localhost:7001/api/rawSqlAddUser HTTP/1.1
token: {{token}}
###
# 原生 SQL 软删除
DELETE http://localhost:7001/api/rawSqlSoftDelUser HTTP/1.1
token: {{token}}
###
# 原生 SQL 硬删除
DELETE http://localhost:7001/api/rawSqlDelUser HTTP/1.1
token: {{token}}

######################################################################################################

### 用户API
# 用户注册
POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
  "username": "测试测试9",
  "nickname": "昵称测试9",
  "email": "邮箱邮箱9",
  "password": "112233",
  "repassword": "112233",
  "fuck1": "fuck1",
  "fuck2": "fuck2",
  "fuck3": "fuck3"
}
###
# 用户登录
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "username": "测试测试6",
  "password": "112233"
}
###
# 用户登出
POST {{baseUrl}}/logout HTTP/1.1
Content-Type: application/json
token: {{token}}
###
# 用户搜索
GET {{baseUrl}}/search?id=15 HTTP/1.1
Content-Type: application/json
token: {{token}}
######################################################################################################
# 申请好友
POST {{baseUrl}}/apply HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "friend_id": 16,
  "lookme": 1,
  "lookhim": 1,
  "nickname": "asd"
}
###
# 申请列表
GET {{baseUrl}}/apply HTTP/1.1
Content-Type: application/json
token: {{token}}
###
# 申请处理
PUT {{baseUrl}}/apply HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "id": 1,
  "status": "agree",
  "lookme": 1,
  "lookhim": 1
}
######################################################################################################
# 好友列表
GET {{baseUrl}}/friend HTTP/1.1
Content-Type: application/json
token: {{token}}
###
# 好友详情
GET {{baseUrl}}/friendDetail?friend_id=14 HTTP/1.1
Content-Type: application/json
token: {{token}}
###
# 好友移入/移除黑名单
POST {{baseUrl}}/friendBlack HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "friend_id": 14,
  "isblack": 0
}
###
# 设置/取消星标好友
POST {{baseUrl}}/friendStar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "friend_id": 14,
  "star": 1
}
###
# 设置朋友圈权限
POST {{baseUrl}}/friendMoment HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "friend_id": 14,
  "lookme": 0,
  "lookhim": 0
}
######################################################################################################
# 添加举报
POST {{baseUrl}}/report HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "reported_id": 14,
  "reported_type": "user",
  "content": "发涩图",
  "category": "违规内容"
}
######################################################################################################
# 添加标签
POST {{baseUrl}}/tag HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "friend_id": 14,
  "tags": "标签1"
}
###
# 获取标签列表
GET {{baseUrl}}/tag HTTP/1.1
Content-Type: application/json
token: {{token}}
######################################################################################################
# 发送消息
POST {{baseUrl}}/ws/send HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "chat_id": 14,
  "chat_type": "user",
  "type": "text",
  "data": "hello"
}
######################################################################################################
# 创建群聊
POST {{baseUrl}}/ws/createGroup HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "ids": [14, 16]
}
###
# 获取离线消息
GET {{baseUrl}}/ws/getOfflineMessage HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "from_id": 15
}